### ISSUE TITLE
what is the test.value meaning?

### ISSUE THREAD

**Issue by liamxg** [IndrajeetPatil/intro-to-ggstatsplot#4]
ggdotplotstats(
  data = movies_long,
  x = budget,
  y = genre,
  test.value = 30
)

**Comment by LiXingguangBrandonStark** [comment]
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/46078579/167878895-4f19880c-f8ac-4ee0-a59d-a2e25efcf591.png">
